---

- name: backup_config
  ios_config:
    backup: yes


- name: Gather router facts
  ios_facts:

- name: Assert that IOS is not compliant to continue with upgrade
  assert:
    that:
      - compliant_ios != ansible_net_version

- name: precheck tshooting commands
  ios_command:
    commands:
      - 'sh log'
      - 'sh int desc'
      - 'sh int status'
      - 'sh mac address-table'
      - 'sh ip route vrf all'
      - 'sh ip int br vrf all'
      - 'sh ip bgp sum'
      - 'sh ip eigrp neigh vrf all'
      - 'sh hsrp brief'
      - 'sh spann summ'
      - 'sh proc cpu his'

  register: ios_precheck_int_brief

- debug: var=ios_precheck.stdout

- name: save output to a file
    copy: content="{{ ios_precheck.stdout }}"  dest="./output/precheck_{{ inventory_hostname }}.txt"