---
- name: router facts after reload
  ios_facts:

- name: Assert that compliant ios is running after reload
  assert:
    that:
      - compliant_ios == ansible_net_version

- name: post upgrade backup_config
  ios_config:
    backup: yes

- name: post check tshoot commands
  ios_command:
    commands:
      - 'show ver'
      - 'show ip int br'
      - 'sh ip eigrp neighbor'
      - 'sh ip route'
      - 'sh run'
      - 'sh ip access-list 102'
      - 'sh ip nat trans'
      - 'sh ip bgp sum'
      - 'sh crypto isakmp sa'
      - 'sh crypto session int'

  register: ios_postcheck